### ISSUE TITLE
Expand doesnt work sometimes

### ISSUE THREAD

**Issue by duczz** [MelleD/lovelace-expander-card#139]
i have 1 issue with this card.

when i create a new card with them integration all works in the edit mode, but when i leave it it doenst work since i close the browser tab and start the brwoser tab again.

any idea?

![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/14396487-ff05-40db-9688-61d2173d4f7c)

![tracklist](https://github.com/MelleD/lovelace-expander-card/assets/25475385/e088b7af-dd4f-409b-8305-56d9a10b3a35)

**Comment by S1M8N** [comment]
Have you test with CTRL + R (Clear browser cache) ?

**Comment by MelleD** [comment]
Should be enough to reload the page again. Have the same issue with other cards sometimes too.
Not sure if i can do something here.

On Mac it's enough to refresh the page with CMD + R

**Comment by duczz** [comment]
I need to Close the Tab and it ist each time when i was in edit Mode, have this Problem only with this Card :/
Whould be great if you find something

**Comment by MelleD** [comment]
@duczz can you try 1.2.10?

**Comment by duczz** [comment]
thanks for testing but it doenst work :(

Edit: it is each time when i click "save" the Card and leave the edit mode (it does not need changes on the card)

**Comment by MelleD** [comment]
@duczz Looks not related to this issue. So again create a bug ticket with more infos

**Comment by MelleD** [comment]
@duczz I cannot reproduce it so I guess you have an old version. Could you check the version on the console?

And please try it again with ignoto modus in browser and press 3 dots "reload resources"

**Comment by duczz** [comment]
i found some new infos for that.

the card works perfect when you create it as a card alone, without any other (stack-in-card etc.), but it works only if you create it alone and not when you had it in a card with multiple other card (stack-in-card) removing the other card does not solve the problem you need really create the card alone, maybe this helps?

Tested in "Horizontal (layout-card)" but does not work in "Section Layout" and "Raster Layout"

Info: you should open the case again :)

![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/6d0a532d-6ecc-4005-b97c-8c3f3b852ff2)

![tracklist](https://github.com/MelleD/lovelace-expander-card/assets/25475385/ac52d3eb-105b-4353-bcf0-d458052344b5)

**Comment by MelleD** [comment]
@duczz sorry but I said try version 1.2.10 and you send a picture where you can easily see that version is 1.2.9???

So what I should say more than use the newest version.

**Comment by duczz** [comment]
the current version is installed, but in den console it shows the old one
![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/218fa72e-89cb-4c08-b20b-3725b4b02813)

**Comment by duczz** [comment]
reinstallation fixed it now, thank you for assist and solve the problem

**Comment by MelleD** [comment]
@duczz this is not related to this integration also for all others.

You HAVE TO reload/refresh the cache or reload resources if you need new versions.
Easier to test is to use inkognito modus without caching. Only the console show you which version is currently in use in the browser. HA show just which version is installed, but NOT which version is in use in OUR browser

**Comment by duczz** [comment]
i know, i does this, i tried different browsers too, but is solved now with a reinstallation.
