### ISSUE TITLE
Change Title Background Color when expanded

### ISSUE THREAD

**Issue by duczz** [MelleD/lovelace-expander-card#148]
when you use multiple expander cards its hard to see which one is currently expanded, it would be great when the activ expanded expander card header has a other color.

so is it possible to add a function thats allow to change the title background color from the expanded card? (only when expanded)

![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/3307ebfb-fb1c-467a-95de-beace6d2d267)

**Comment by MelleD** [comment]
@duczz 
open
<img width="539" alt="Bildschirmfoto 2024-06-15 um 09 39 33" src="https://github.com/MelleD/lovelace-expander-card/assets/6340898/4665ea86-2e82-4d55-a346-54284c8cec7b">


``` 
        type: custom:expander-card
        title: "Räume"
        expander-card-background-expanded: "#ffffff12 radial-gradient(circle, transparent 1%, #ffffff12 1%)"```

**Comment by duczz** [comment]
Perfect, looks good 👍🏻👍🏻
Is it possible to Change the color only from the top Line (Räume ) too?
Currentlly it looks like it change the General backgroundcolor without the entities

**Comment by MelleD** [comment]
Yes only the complete background. The other option for the button looked weired when you have padding. But if you see the PR you could also easily add a option for button background expanded.

IMHO this make more sense because you can the group which is related to the expander make also sense when you have more than one

**Comment by duczz** [comment]
Alright thank you 👍🏻

**Comment by MelleD** [comment]
What I would like to try is to make the state open/closed into a var.
Maybe then you can do everything what you want with card mod if you have the state —var(open)

But I have no experience to expose variables to card mod and have to test it when I have some time ;)

**Comment by duczz** [comment]
That would be cool, that makes it much more flexible 👍🏻
