### ISSUE TITLE
Add Code-Editor Button to Title Card

### ISSUE THREAD

**Issue by duczz** [MelleD/lovelace-expander-card#149]
**Describe the solution you'd like**
Currently we need to use the card-editor from the integration to modify the title card (card_mod for example)

**Describe alternatives you've considered**
Is it possible to add a Code-Editor Button directlly to the title Card too, to modify the title card better?

**Additional context**
![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/59ef02a7-f51b-46ec-aee2-6f1913fdc501)

**Comment by MelleD** [comment]
@duczz we should a little bit work on the description of feature requests. Please add more context the template already help you to fill out a feature request.

**Comment by duczz** [comment]
okay, so you are missing the point why i want this feature:

with this second Code-editor is it easyer to modify the title card, currently we need to use the card-editor from the integration, it make it easier when the title card has an seperate code-editor if this is possible.

edit: this is only my oppinion, that it makes a little bit easier, when it is to heavy to integrat it is okay too :)

**Comment by MelleD** [comment]
> okay, so you are missing the point why i want this feature:

For example:

"
Summary:
As a user, I would like to have a separate code editor for modifying the title card. This would simplify the process and make it more efficient compared to using the card editor from the integration.

Description:
Currently, modifying the title card requires using the card editor from the integration, which can be cumbersome and less intuitive. Having a dedicated code editor specifically for the title card would streamline the workflow and improve the user experience. This dedicated editor should be easily accessible and user-friendly, allowing for quicker and more precise adjustments to the title card.
"

Yes more context help also to figure out if other people have the same issue/opinion. 
Then we can decide how and when we can implement it.

I'am using only yaml, that's user friendly for this card :P

**Comment by illuzn** [comment]
This is also potentially a bug/ annoyance as well as a feature request.

### Bug

Show visual editor button is incorrectly disabled if at least 1 sub-card does not support visual editor (and stays disabled incorrectly).

### Reproduction Steps

1. Create an expander card.
2. Put any card which is visually editable on that expander (I used tile).
3. Add any card which is _not_ visually editable to that expander (I used entity filter).
4. Visual editing is now disabled for all cards.
5. Save the expander card.
6. Edit the expander card.
7. Visual editing is now enabled for the tile card.
8. Select the entity filter card to edit it.
9. Visual editing is now disabled for all cards.

### Proposed solution

Mimic the behaviour of the grid card i.e.

1. Have a global show code/ visual editor button at the bottom (this already exists and only its behaviour to deal with the above needs to be fixed).
2. For each card have a separate small show code/ visual editor which only toggles for that individual card.
