### ISSUE TITLE
More Cards long Opening

### ISSUE THREAD

**Issue by milandzuris** [MelleD/lovelace-expander-card#159]
**Checklist:**

- [ * ] I updated to the latest version available
- [ * ] I cleared the cache of my browser

**Description of problem:**
Hi, when i open first time Dashboard where is more Expander Cards this Dashboard takes a very long time to open 10-30sec

**Comment by MelleD** [comment]
Please can you create a [minimally reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example.)? 
How long does it take to load the dashboard without an expander card?

Please provide the info from the template

**Comment by milandzuris** [comment]
> Please can you create a [minimally reproducible example](https://en.wikipedia.org/wiki/Minimal_reproducible_example.)? How long does it take to load the dashboard without an expander card?
> 
> Please provide the info from the template

Hi, i think there is problem i have many expander card in one dashboard, and there is chance add to setting do not load the card if it is not open?

**Comment by milandzuris** [comment]
23 expander cards, [with this older card i dont have so long loading](https://github.com/Alia5/lovelace-expander-card)

![image](https://github.com/MelleD/lovelace-expander-card/assets/42905545/afab5f32-2b22-49d5-b132-4c4a2310287b)

**Comment by MelleD** [comment]
Not reproducible. Try it with >50 works fine.

![Bildschirmfoto 2024-07-02 um 07 43 09](https://github.com/MelleD/lovelace-expander-card/assets/6340898/a1e1b69d-922f-45d2-9bfc-961347991c9b)

Without example I cannot say more
