### ISSUE TITLE
Resize default Padding value

### ISSUE THREAD

**Issue by duczz** [MelleD/lovelace-expander-card#166]
Currently the Padding from expander is very big 16px, when you can resize it we have more space in the card

**Describe the solution you'd like**
Currently the default padding is 16px, i think 8px would be better

**Describe alternatives you've considered**
Is it possible to resize the default padding to 8px?

**Additional context**
See the green mark around the expander card
![image](https://github.com/MelleD/lovelace-expander-card/assets/25475385/17d2fee9-a0c6-45b8-9624-957eda66657d)

**Comment by MelleD** [comment]
Not sure which padding you mean, but you can set the padding of the card see README.MD
https://github.com/MelleD/lovelace-expander-card

option: padding, child-padding, title-card-padding

**Comment by duczz** [comment]
Aah sorry "ha-card Type: entities", its the entities padding, my misstake. 😞

**Comment by MelleD** [comment]
No problem
