### ISSUE TITLE
title-card-clickable for touch input

### ISSUE THREAD

**Issue by Caligo82** [MelleD/lovelace-expander-card#187]
**Is your feature request related to a problem? Please describe.**
I'm trying to make the "title-card-clickable" work for touch inputs. However it is either not supported or I'm doing it wrong...

**Describe the solution you'd like**
I'd like for the expander card to expand with touch input while a title card is selected and "title-card-clickable" is set to true.

**Describe alternatives you've considered**
Since there's no manual "expand card xy" action I struggle to implement an alternative with a button action.

**Additional context**
It works with mouse clicks. Just not with touch.

**Comment by MelleD** [comment]
I have no idea, why this listener is not added for touch.
https://github.com/MelleD/lovelace-expander-card/blob/main/src/ExpanderCard.svelte#L96
Maybe anybody else have experience and can help

**Comment by Caligo82** [comment]
At least in my config it's not working with 1.6.0 I'm afraid...

**Comment by MelleD** [comment]
> At least in my config it's not working with 1.6.0 I'm afraid...

As always you have to refresh and delete your cache or try it in private ingocnito browser.
Without log and info from your console I can say not more.

For iOS App it take 1-2 days till they download the new version. No idea why have the same issue for other cards

**Comment by Caligo82** [comment]
Even cleared cache, tried incognito... to no avail. 
I'm using a picture card for this. Tried a new card as well. No luck there.
What logs are you looking for?

**Comment by MelleD** [comment]
Can you check the browser console which version? 

Let me check with picture card maybe there is an issue that the event goes not to the child

EDIT: Maybe I found a better solution let me try this. With iOS touch looks good

**Comment by Caligo82** [comment]
It is using the latest version:

![image](https://github.com/MelleD/lovelace-expander-card/assets/31889595/5aca40f6-47f2-494f-8dfb-372402e6fb38)

It also doesn't work with F12 and Mobile View... maybe that helps debugging.

**Comment by Caligo82** [comment]
It was Release [1.6.1](https://github.com/MelleD/lovelace-expander-card/releases/tag/1.6.1) that fixed it.
Other than that: works perfect. Thank you!

**Comment by Caligo82** [comment]
Ok, one fun issue remains. It's quite impossible to scroll now. Every touch will activate an expand action. 
Is this fixable? 😆

**Comment by MelleD** [comment]
Do you have an example and picture? 

Maybe using touchend instead of touchstart
https://www.w3schools.com/jsref/event_touchstart.asp

**Comment by MelleD** [comment]
Yes it not so easy(maybe new bug ticket to track it) but you habe to save the element on touchstart and check if it is the same on touchend.
Maybe you can prepare a PR or I have time tomorrow
