### ISSUE TITLE
Distinguish touch from scroll action if "title-card-clickable" is set to true

### ISSUE THREAD

**Issue by Caligo82** [MelleD/lovelace-expander-card#190]
**Is your feature request related to a problem? Please describe.**

After setting the "title-card-clickable" to "true" for a picture card, it will also expand the card if a scroll action is performed. This has some unintended consequences.

**Describe the solution you'd like**

It should be possible to distinguish a touch from a scroll action.

**Describe alternatives you've considered**

I tried GPT 4o, it recommended something like this:

```
// Variables to track touch state
let touchStartX = 0;
let touchStartY = 0;
let touchStartTime = 0;
const touchThreshold = 10; // Distance threshold to distinguish scroll from tap
const timeThreshold = 200; // Time threshold for a quick tap

const card = document.querySelector('.expander-card');

// Add touchstart event listener
card.addEventListener('touchstart', (event) => {
  touchStartX = event.touches[0].clientX;
  touchStartY = event.touches[0].clientY;
  touchStartTime = new Date().getTime();
}, { passive: true });

// Add touchmove event listener
card.addEventListener('touchmove', (event) => {
  const touchMoveX = event.touches[0].clientX;
  const touchMoveY = event.touches[0].clientY;

  const deltaX = Math.abs(touchMoveX - touchStartX);
  const deltaY = Math.abs(touchMoveY - touchStartY);

  if (deltaX > touchThreshold || deltaY > touchThreshold) {
    // It's a scroll, do nothing special
    return;
  }
}, { passive: true });

// Add touchend event listener
card.addEventListener('touchend', (event) => {
  const touchEndTime = new Date().getTime();
  const deltaTime = touchEndTime - touchStartTime;

  const touchEndX = event.changedTouches[0].clientX;
  const touchEndY = event.changedTouches[0].clientY;

  const deltaX = Math.abs(touchEndX - touchStartX);
  const deltaY = Math.abs(touchEndY - touchStartY);

  if (deltaTime < timeThreshold && deltaX < touchThreshold && deltaY < touchThreshold) {
    // It's a tap, expand the card
    toggleCardExpansion(card);
  }
}, { passive: true });

// Function to toggle the card expansion
function toggleCardExpansion(card) {
  card.classList.toggle('expanded');
}
```
with this explanation:

> touchstart: Captures the initial touch coordinates and timestamp.
touchmove: Monitors the movement to identify if the touch is a scroll. If the movement exceeds a certain threshold, it is considered a scroll.
touchend: Checks if the touch event qualifies as a tap based on the distance moved and the duration. If so, it triggers the expand functionality.

**Additional context**

Maybe there's a preset to use here?

TIP: You can always edit your issue if it isn't formatted correctly.
     See https://guides.github.com/features/mastering-markdown

**Comment by MelleD** [comment]
@Caligo82 works?

**Comment by Caligo82** [comment]
Oh yes absolutely. Thank you very much!
