### ISSUE TITLE
Card Was Created Without Expected Prop 'hass'

### ISSUE THREAD

**Issue by thomasmaxson** [MelleD/lovelace-expander-card#198]
I have been getting the following JavaScript _warning_ with the Expander Card addon. Simply load the page, and the following warning shows within the browser console. Is anyone else receiving this?

```
<expander-sub-card> was created without expected prop 'hass'
(anonymous) @ expander-card.js?hacstag=677140532162:1
```

**Comment by MelleD** [comment]
Yes this line is the issue
https://github.com/MelleD/lovelace-expander-card/blob/main/src/Card.svelte#L48

https://stackoverflow.com/questions/58571604/componentname-was-created-without-expected-prop-segment

I think there is a missing export before loading

**Comment by thomasmaxson** [comment]
Thank you for the quick fix. Much appreciated!

**Comment by MelleD** [comment]
No it’s not working. I tried a lot of things but no idea what the issue is.
