### ISSUE TITLE
Last update (2.1.0) causes huge loading times on dashboard.

### ISSUE THREAD

**Issue by NeeeeB** [MelleD/lovelace-expander-card#260]
![image](https://github.com/user-attachments/assets/e822b4a4-861b-4d43-8351-6f9c530d0828)

A picture is better than a thousand words...
PS: downgrading to previous version (2.0.1) fixes the problem.

**Comment by MelleD** [comment]
The display has changed. In the previous version loading was not displayed accurately. Now it is more transparent.

However, I also subjectively have the feeling that loading has become slower when you have a lot of components.
However, nothing was changed in the code just an upgrade was made from Svelte 3 to Svelte 4.

In a current branch I even upgraded to Svelte 5. It got a little better, but here too it was probably faster with Svelte 3.

Actually, the two major releases from Svelte were exactly there to get better performance. For this reason it is currently difficult to say what exactly is the problem. Maybe there will be someone who knows a lot about it and will discover something.

**Comment by NeeeeB** [comment]
For me it is major slowdown unfortunately...
For example this card : 
![image](https://github.com/user-attachments/assets/7705f096-6629-4c11-804e-b8b6e2a59059)
which has this configuration (nothing really huge or fancy) : 

**type: custom:expander-card
gap: 0.6em
padding: 1em
clear: false
title: Expander
overlay-margin: 0.5em
child-padding: ''
button-background: transparent
title-card:
  type: entities
  entities: []
  title: Lumières Maison
  icon: mdi:lightbulb-group
  show_header_toggle: false
  card_mod:
    style: |
      ha-card .card-header {
        padding: 0px;
        display: unset;
      }
      ha-card .card-header .name {
        text-align: center;
        color: #D25F36;
      }
show_header_toggle: false
cards:
  - type: vertical-stack
    cards:
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-entity-card
            entity: switch.salon
            icon_color: deep-orange
            hold_action:
              action: none
            double_tap_action:
              action: none
            tap_action:
              action: toggle
          - type: custom:mushroom-entity-card
            entity: switch.journuit
            icon_color: deep-orange
            hold_action:
              action: none
            double_tap_action:
              action: none
            tap_action:
              action: toggle
      - type: horizontal-stack
        cards:
          - type: custom:mushroom-entity-card
            entity: switch.cuisine
            icon_color: deep-orange
            hold_action:
              action: none
            double_tap_action:
              action: none
            tap_action:
              action: toggle
          - type: custom:mushroom-entity-card
            entity: switch.maison
            icon_color: deep-orange
            tap_action:
              action: toggle
            hold_action:
              action: none
            double_tap_action:
              action: none
expanded: false
title-card-button-overlay: false
card_mod:
  style: |
    ha-card .card-header {
      padding: 0px;
      display: unset;
    }
    ha-card .card-header .name {
      text-align: center;
      color: #D25F36;
    }**

takes 3 to 4 seconds to display (loading...) with 2.1.0 version, where it is almost instant with version 2.0.1

And I can not blame the hardware, I do have HAOS running on an Intel N100 with 8GG RAM, purely dedicated to HA.

I'll stick to 2.0.1 for the time being because I don't wanna ruin my dashboard experience, considering it is made with expander-card at 90%...

**Comment by Jyers** [comment]
I can confirm that I am experiencing the same issue. Even with very simple card configurations with just 3-4 entities I am seeing loading times in excess of 5 seconds. Rolling back to 2.0.1 fixed it. On 2.0.1 I also tested interacting with the cards immediately on load and they don't seem to be "faking" being loaded, they are fully interactable the second I reload.
