### ISSUE TITLE
Not displaying correctly since update to 2.2.0


### ISSUE THREAD

**Issue by robertboccia** [MelleD/lovelace-expander-card#270]
![Screenshot_20240930_214505_Home Assistant.jpg](https://github.com/user-attachments/assets/1974300d-410b-4129-a95b-0a96d70641a1)

**Comment by MelleD** [comment]
Read the explanation how to open a bug ticket. Without description it make no sense

**Comment by robertboccia** [comment]
You can clearly see the issue in the screen shot from the mobile companion app in the picture I have attached before it used to have a border around the expander card now that's gone

**Comment by MelleD** [comment]
Sorry, learn to open a ticket with a description and read the description of the template. Otherwise it won't be processed.
