### ISSUE TITLE
Card Keeps Refreshing, Only YAML editing possible 

### ISSUE THREAD

**Issue by yjamal01** [MelleD/lovelace-expander-card#29]
Like the original this is forked from, there is an issue with the card refreshing constantly when editing 

This makes it impossible to use, and have to edit in YAML to prevent the refresh

**Comment by ddetton** [comment]
> Like the original this is forked from, there is an issue with the card refreshing constantly when editing
> 
> This makes it impossible to use, and have to edit in YAML to prevent the refresh

Same issue for me.  Wish I knew how to code in svelte.

**Comment by Anabcent** [comment]
I am using the following fork https://github.com/spencermamer/lovelace-yet-another-expander-card which seems to work

**Comment by ddetton** [comment]
Thanks!  Does this one have the bug fixed where it does a screen refresh every 10-15s when it has a title card?

**Comment by versile2** [comment]
It is definitely related to title card

**Comment by NeeeeB** [comment]
> It is definitely related to title card

Yes it is.
If you add an Expander card without Title Card, no problem at all.

Looks like the OA tried to circumvent it in the past with this commit, which is exactly the time of the "refresh" (5 sec) :
https://github.com/MelleD/lovelace-expander-card/commit/2fd6b8ac7051d998d6928bbc166630fa4c2254f5

**Comment by MelleD** [comment]
Fixed with 1.0.0

**Comment by rubin110** [comment]
With 1.0.2 I cannot reproduce the issue. Thank you!

**Comment by yjamal01** [comment]
> Fixed with 1.0.0

Where do we donate? This is one of the few custom integrations that my dashboard relies heavily on and I'd love to contribute to its ongoing support. Unfortunately I know nothing about coding so that contribution would only be monetary, but I do not see any link on your github.

**Comment by MelleD** [comment]
I wanted to fix the two known bugs first before I update the README. I just forked the repo so there is a little work todo. I wanted to upgrade all deps but the last major Svelte version probably doesn't work for some reason :(.
This cost me a lot of time, but thanks for your offer 👍👍👍.
So first let me fix the last known bug ( I hope I can) and I have to fix all links in the readme.

**Comment by MelleD** [comment]
Hello everyone,

I have solved all known bugs and updated the README.
I will now gradually update the individual dependencies.

If anyone has problems, just open a new ticket.

Have fun

**Comment by Sensorn** [comment]
Put an expander card on my dashboard today and i love it. I get that refreshing bug when adding a title card though. Any way to solve this?

**Comment by MelleD** [comment]
> Put an expander card on my dashboard today and i love it. I get that refreshing bug when adding a title card though. Any way to solve this?

I increased the timeout again. Try 1.2.11 if this not helps please create a bug ticket with more info. I cannot reproduce the issue
